event_inherited();
weapon_type = "pistol";
weapon_recoil = 4;
ammo_max =11;
ammo_count = ammo_max;
bullet_type = "regular";
bullet_damage = 1;
bullet_speed = 8;
possessed = false;
can_shoot = true;
outline_sprite = spr_pistol_outline;