event_inherited();
weapon_type = "biggun2";
weapon_recoil = 4;
ammo_count = 999;
ammo_max = ammo_count;
bullet_type = "regular";
bullet_damage = 1;
bullet_speed = 8;
possessed = false;
can_shoot = true;
outline_sprite = spr_turret_head_outline;
firedelay = 10;