hint_msg[0] = "Use the LEFT MOUSE to \npush your weapon with recoil!"
hint_msg[1] = "Use the RIGHT MOUSE to \nshoot without recoil."
hint_msg[2] = "When killed, enemies drop their weapon."
hint_msg[3] = "Shotguns are great for fast movement,\nhowever they only have two shells."
hint_msg[4] = "Looks like the enemies are trying to stop you,\nYou have to stop them!"
hint_msg[5] = "The turrets provide endless ammo,\nuse them to your advantage!"
hint_msg[6] = "Press R to RESTART the current level\nif you are stuck!"
hint_msg[7] = "When close enough to one, hover \nover a weapon with your\nMOUSE and press SPACE to possess it!"
hint = -1;
msg_num = 0;
msg_time = 600;
msg_timer = msg_time;
popup_x = 600;