weapon_type = "undefined";
weapon_recoil = 0;
ammo_max = 0;
ammo_count = 0;
bullet_type = noone;
bullet_damage = 0;
bullet_speed = 0;
possessed = false;
can_shoot = false;
h_speed = 0;
v_speed = 1;
weapon_gravity = 0.15;  //try this with 0.1 and tell me if it feels worse/better for control - Ani
grounded = false;
firedelay = 0;          //in frames