weapon_type = "undefined";
weapon_recoil = 0;
bullet_type = noone;
bullet_damage = 0;
bullet_speed = 0;
ammo_max = 1000;
ammo_count = ammo_max;
possessed = false;
can_shoot = false;
h_speed = 0;
v_speed = 1;
weapon_gravity = 0.15;
grounded = false;
firedelay = 0;  //in frames
selected = false;
outline_sprite = -1;
fake_angle = 0;
image_speed = 0;